version: '3.8'

services:
  auth-service:
    build: 
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    restart: unless-stopped
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://host.docker.internal:27017/secure_file_sharing
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "8080:8080"
    networks:
      - secure-file-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/health/service"]
      interval: 30s
      timeout: 10s
      retries: 3
    platform: linux/amd64

networks:
  secure-file-network:
    driver: bridge